language: go
sudo: true
go:
  - 1.7
  - 1.8
go_import_path: github.com/uber/zanzibar
env:
  global:
    - GO15VENDOREXPERIMENT=1
    - TEST_TIMEOUT_SCALE=10
cache:
  directories:
    - vendor
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -qq time
  - sudo apt-get install -qq build-essential libssl-dev git
  - sudo apt-get install -qq libluajit-5.1-2 libluajit-5.1-common
  - wget http://us.archive.ubuntu.com/ubuntu/pool/universe/w/wrk/wrk_4.0.1-2_amd64.deb
  - sudo dpkg -i wrk_4.0.1-2_amd64.deb
install:
  - make install
script:
  - make generate
  - make check-generate
  - make lint
  - make test-only
  - make cover
  - make fast-bench
  - make bins
  - make test-benchmark-runner
after_success:
  - make travis-coveralls
