config:
  path: github.com/uber/zanzibar/examples/selective-gateway/middlewares/default/default_example
  schema: ./middlewares/default/default_example/default_example_schema.json
dependencies:
  client:
  - echo
name: default_example
type: http
