config:
  exposedMethods:
    SaveContacts: Contacts::saveContacts
    TestURLURL: Contacts::testUrlUrl
  fixture:
    importPath: github.com/uber/zanzibar/examples/example-gateway/clients/contacts/fixture
    scenarios:
      SaveContacts:
      - success
  idlFile: clients/contacts/contacts.thrift
  idlFileSha: '{{placeholder}}'
  customInterface: Client
name: contacts
type: http
