env: production
envVarsToTagInRootScope: []
jaeger.disabled: false
jaeger.reporter.flush.milliseconds: 10000
jaeger.reporter.hostport: localhost:6831
jaeger.sampler.param: 0.001
jaeger.sampler.type: remote
metrics.flushInterval: 1000
metrics.m3.hostPort: 127.0.0.1:9052
metrics.m3.includeHost: true
metrics.m3.maxPacketSizeBytes: 1440
metrics.m3.maxQueueSize: 10000
metrics.runtime.collectInterval: 1000
metrics.runtime.enableCPUMetrics: true
metrics.runtime.enableGCMetrics: true
metrics.runtime.enableMemMetrics: true
metrics.type: m3
service.env.config: {}
subLoggerLevel.http: info
subLoggerLevel.jaeger: info
subLoggerLevel.tchannel: info
useDatacenter: false
#Some tchannel clients have retryCount functionality, this feature will be disabled by default
tchannelclients.retryCount.feature.enabled: false
