clients.bar.defaultHeaders:
  X-Client-ID: bar
clients.bar.ip: 127.0.0.1
clients.bar.port: 4001
clients.bar.timeout: 10000
clients.baz.ip: 127.0.0.1
clients.baz.port: 4002
clients.baz.serviceName: Qux
clients.baz.timeout: 10000
clients.baz.timeoutPerAttempt: 2000
clients.baz.maxConcurrentRequests: 1000
clients.baz.errorPercentThreshold: 20
clients.baz.sleepWindowInMilliseconds : 5000
clients.baz.requestVolumeThreshold : 20
clients.contacts.ip: 127.0.0.1
clients.contacts.port: 4000
clients.contacts.timeout: 10000
clients.contacts.maxConcurrentRequests: 1000
clients.contacts.errorPercentThreshold: 20
clients.corge-http.serviceName: CorgeHttp
clients.corge-http.maxConcurrentRequests: 1000
clients.corge-http.errorPercentThreshold: 20
clients.corge.serviceName: Corge
clients.corge.timeout: 10000
clients.corge.timeoutPerAttempt: 2000
clients.corge.maxConcurrentRequests: 1000
clients.corge.errorPercentThreshold: 20
clients.google-now.ip: 127.0.0.1
clients.google-now.port: 14120
clients.google-now.timeout: 10000
clients.google-now.circuitBreakerDisabled: true
clients.googleNowTChannel.connectionType: p2p
clients.googleNowTChannel.hostList:
- 127.0.0.1:4002
clients.googleNowTChannel.timeout: 10000
clients.googleNowTChannel.maxConcurrentRequests: 1000
clients.googleNowTChannel.errorPercentThreshold: 20
clients.multi.ip: 127.0.0.1
clients.multi.port: 4003
clients.multi.timeout: 10000
clients.multi.maxConcurrentRequests: 1000
clients.multi.errorPercentThreshold: 20
clients.withexceptions.ip: 127.0.0.1
clients.withexceptions.port: 4004
clients.withexceptions.timeout: 10000
clients.withexceptions.maxConcurrentRequests: 1000
clients.withexceptions.errorPercentThreshold: 20
envVarsToTagInRootScope: []
http.port: 7783
http.clients.requestUUIDHeaderKey: x-request-uuid
logger.fileName: /var/log/example-gateway/example-gateway.log
logger.output: disk
metrics.serviceName: example-gateway
metrics.m3.includeHost: true
service.env.config: {}
serviceName: example-gateway
sidecarRouter.default.grpc.ip: 127.0.0.1
sidecarRouter.default.grpc.port: 4998
sidecarRouter.default.http.calleeHeader: RPC-Service
sidecarRouter.default.http.callerHeader: RPC-Caller
sidecarRouter.default.http.ip: 127.0.0.1
sidecarRouter.default.http.port: 4999
sidecarRouter.default.tchannel.ip: 127.0.0.1
sidecarRouter.default.tchannel.port: 5000
tchannel.port: 7784
tchannel.processName: example-gateway
tchannel.serviceName: example-gateway
tchannel.clients.requestUUIDHeaderKey: x-request-uuid
useDatacenter: false
clients.baz.alternates:
  routingConfigs:
    - headerName: x-container
      headerValue: ^sandbox$
      serviceName: basicSandbox
      rd: reverse-proxy
    - headerName: x-test-env
      headerValue: ^sandbox$
      serviceName: nomatch
  servicesDetail:
    basicSandbox:
      ip: 127.0.0.1
      port: 8113
    nomatch:
      ip: 127.0.0.1
      port: 8114
grpc.clientServiceNameMapping:
  echo: echo
