clients.bar.defaultHeaders:
  X-Client-ID: bar
clients.bar.ip: 127.0.0.1
clients.bar.port: 4001
clients.bar.timeout: 10000
clients.bar.followRedirect: false
clients.baz.ip: 127.0.0.1
clients.baz.port: 4002
clients.baz.serviceName: Qux
clients.baz.timeout: 10000
clients.baz.timeoutPerAttempt: 2000
clients.baz.maxConcurrentRequests: 1000
clients.baz.errorPercentThreshold: 20
clients.baz.sleepWindowInMilliseconds : 5000
clients.baz.requestVolumeThreshold : 20
clients.contacts.ip: 127.0.0.1
clients.contacts.port: 4000
clients.contacts.timeout: 10000
clients.contacts.maxConcurrentRequests: 1000
clients.contacts.errorPercentThreshold: 20
clients.corge.serviceName: Corge
clients.corge.timeout: 10000
clients.corge.timeoutPerAttempt: 2000
clients.corge.maxConcurrentRequests: 1000
clients.corge.errorPercentThreshold: 20
clients.echo.timeout: 20
clients.google-now.ip: 127.0.0.1
clients.google-now.port: 14120
clients.google-now.timeout: 10000
clients.google-now.circuitBreakerDisabled: true
clients.googleNowTChannel.connectionType: p2p
clients.googleNowTChannel.hostList:
  - 127.0.0.1:4002
clients.googleNowTChannel.timeout: 10000
clients.googleNowTChannel.maxConcurrentRequests: 1000
clients.googleNowTChannel.errorPercentThreshold: 20
clients.multi.ip: 127.0.0.1
clients.multi.port: 4003
clients.multi.timeout: 10000
clients.multi.maxConcurrentRequests: 1000
clients.multi.errorPercentThreshold: 20
clients.withexceptions.ip: 127.0.0.1
clients.withexceptions.port: 4004
clients.withexceptions.timeout: 10000
clients.withexceptions.maxConcurrentRequests: 1000
clients.withexceptions.errorPercentThreshold: 20
contextlogger.zanzibar.skiplogs: false
env: test
envVarsToTagInRootScope: []
http.defaultHeaders:
  Accept: application/json
  Content-Type: application/json
http.port: 0
http.clients.requestUUIDHeaderKey: x-request-uuid
logger.fileName: /tmp/example-gateway.log
logger.output: disk
logger.level: debug
metrics.serviceName: example-gateway
metrics.m3.includeHost: false
service.env.config: {}
serviceName: example-gateway
shutdown.pollInterval: 10
sidecarRouter.default.grpc.ip: 127.0.0.1
sidecarRouter.default.grpc.port: 4998
sidecarRouter.default.http.calleeHeader: RPC-Service
sidecarRouter.default.http.callerHeader: RPC-Caller
sidecarRouter.default.http.ip: 127.0.0.1
sidecarRouter.default.http.port: 4999
sidecarRouter.default.tchannel.ip: 127.0.0.1
sidecarRouter.default.tchannel.port: 5000
tchannel.port: 0
tchannel.processName: example-gateway
tchannel.serviceName: example-gateway
tchannel.clients.requestUUIDHeaderKey: x-request-uuid
useDatacenter: false
clients.baz.alternates:
  routingConfigs:
    - headerName: x-container
      headerValue: ^sandbox$
      serviceName: basicSandbox
    - headerName: x-test-env
      headerValue: ^sandbox$
      serviceName: nomatch
  servicesDetail:
    basicSandbox:
      ip: 127.0.0.1
      port: 8113
    nomatch:
      ip: 127.0.0.1
      port: 8114
grpc.clientServiceNameMapping:
  echo: echo
service.shadow.env.override.enable: true
circuitbreaking-configurations:
  levels:
    '1': '0-99'
    '2': '100-999'
    '3': '1000-9999'
    '4': '10000+'
  parameters:
    'default':
      sleepWindowInMilliseconds: 5000
      errorPercentThreshold: 20
      requestVolumeThreshold: 20
      maxConcurrentRequests: 20
    '1':
      sleepWindowInMilliseconds: 7000
      errorPercentThreshold: 10
      requestVolumeThreshold: 15
      maxConcurrentRequests: 20
    '2':
      sleepWindowInMilliseconds: 4000
      errorPercentThreshold: 15
      requestVolumeThreshold: 22
      maxConcurrentRequest: 20
    '3':
      sleepWindowInMilliseconds: 3000
      errorPercentThreshold: 25
      requestVolumeThreshold: 24
      maxConcurrentRequests: 25
    '4':
      sleepWindowInMilliseconds: 1000
      errorPercentThreshold: 30
      requestVolumeThreshold: 25
      maxConcurrentRequests: 30
dedicated.tchannel.client: true
apiEnvironmentHeader: x-api-environment
